export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  lightGray: '#DCDCDC',
  accent: '#FFC231',
  accentRed: '#FB5D2E',
  accentPink: '#F96165',
};

export const Categories = [
  {
    name: 'Burger',
    image: require('../database/images/burger.png'),
    items: [
      {
        name: 'Classic Burger',
        weight: 120,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/burger/classicburger.png'),
        size: 'Large 8"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        name: 'Aloo Tikki Burger',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/alootikkiburger.png'),
        size: 'Large 12"',
        crust: 'Thick Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        name: 'Biggie Cheese Burger',
        weight: 250,
        rating: '4.2',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/burger/biggiecheese.png'),
        size: 'Large 10"',
        crust: 'Thick Crust',
        delivery: 35,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('../database/images/pizza.png'),
    items: [
      {
        name: 'Pepperoni Pizza',
        weight: 250,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../database/images/Tomato.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
        ],
      },
      {
        name: 'Plain Cheese Pizza',
        weight: 300,
        rating: '4.5',
        price: 299,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
        ],
      },
      {
        name: 'Mexican Green Wave',
        weight: 350,
        rating: '4.7',
        price: 499,
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 15"',
        crust: 'Thin Crust',
        delivery: 25,
        ingredients: [
          require('../database/images/flour.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/Sliced-Onion.png'),
        ],
      },
    ],
  },
  {
    name: 'Soft Drinks',
    image: require('../database/images/softdrinks.png'),
    items: [
      {
        name: 'Coca Cola',
        weight: 200,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/softdrinks/cocacola.png'),
        size: 'Medium Glass"',
        crust: 'Small Ice',
        delivery: 10,
        ingredients: [require('../database/images/softdrinks/cocacola.png')],
      },
      {
        name: 'Orange Juice',
        weight: 500,
        rating: '4.8',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/orange.png'),
        size: 'Large Glass"',
        crust: 'Large Ice',
        delivery: 8,
        ingredients: [require('../database/images/softdrinks/orange.png')],
      },
      {
        name: 'Mango Juice',
        weight: 150,
        rating: '4.5',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/softdrinks/mango.png'),
        size: 'Large Glass"',
        crust: 'Large Ice',
        delivery: 5,
        ingredients: [require('../database/images/softdrinks/mango.png')],
      },
    ],
  },
  {
    name: 'Biryani',
    image: require('../database/images/biryani.png'),
    items: [
      {
        name: 'Chicken Biryani',
        weight: 180,
        rating: '4.3',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/biryani/chickenbiryani.png'),
        size: 'Medium',
        crust: 'Fried Onion',
        delivery: 20,
        ingredients: [
          require('../database/images/biryani/ingredients/chicken.png'),
          require('../database/images/biryani/ingredients/masale.png'),
          require('../database/images/biryani/ingredients/onion.png'),
          require('../database/images/biryani/ingredients/rice.png'),
        ],
      },
      {
        name: 'Hydrabadi Chicken Biryani',
        weight: 180,
        rating: '5.0',
        price: 299,
        isTopOfTheWeek: true,
        image: require('../database/images/biryani/hyadrabadi.png'),
        size: 'Medium',
        crust: 'Fried Onion',
        delivery: 30,
        ingredients: [
          require('../database/images/biryani/ingredients/chicken.png'),
          require('../database/images/biryani/ingredients/rice.png'),
          require('../database/images/biryani/ingredients/masale.png'),
          require('../database/images/biryani/ingredients/onion.png'),
        ],
      },
      {
        name: 'Chicken Dum Biryani',
        weight: 180,
        rating: '4.6',
        price: 199,
        isTopOfTheWeek: false,
        image: require('../database/images/biryani/chickenbiryani.png'),
        size: 'Medium',
        crust: 'Fried Onion',
        delivery: 45,
        ingredients: [
          require('../database/images/biryani/ingredients/rice.png'),
          require('../database/images/biryani/ingredients/chicken.png'),
          require('../database/images/biryani/ingredients/onion.png'),
          require('../database/images/biryani/ingredients/masale.png'),
        ],
      },
    ],
  },
  {
    name: 'Dessert',
    image: require('../database/images/dessert.png'),
    items: [
      {
        name: 'Vanilla Ice Cream',
        weight: 60,
        rating: '4.3',
        price: 80,
        isTopOfTheWeek: false,
        image: require('../database/images/dessert/vanilla.png'),
        size: 'Medium Scope',
        crust: 'No Crust',
        delivery: 2,
        ingredients: [
          require('../database/images/dessert/ingredients/milk.png'),
          require('../database/images/dessert/ingredients/vanillaextract.png'),
        ],
      },
      {
        name: 'Frutti Di Bosco',
        weight: 100,
        rating: '4.3',
        price: 99,
        isTopOfTheWeek: false,
        image: require('../database/images/dessert/fruttidibosco.png'),
        size: 'Medium Scope',
        crust: 'No Crust',
        delivery: 5,
        ingredients: [
          require('../database/images/dessert/ingredients/blueberry.png'),
          require('../database/images/dessert/ingredients/chocolate.png'),
          require('../database/images/dessert/ingredients/milk.png'),
          require('../database/images/dessert/ingredients/dryfruits.png'),
        ],
      },
      {
        name: 'Mangnum Cones',
        weight: 150,
        rating: '5.0',
        price: 199,
        isTopOfTheWeek: true,
        image: require('../database/images/dessert/magnumcones.png'),
        size: 'Medium',
        crust: 'Thin Chocolate',
        delivery: 2,
        ingredients: [
          require('../database/images/dessert/ingredients/milk.png'),
          require('../database/images/dessert/ingredients/chocolate.png'),
        ],
      },
    ],
  },
];
